server:
  port: 40612

spring:
  datasource:
      name: auth_manager
      url: jdbc:mysql://127.0.0.1:3306/auth_manager?useUnicode=true&characterEncoding=utf8
      username: root
      password: adminadmin
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mappers/*Mapper.xml

