server:
  port: 40612

com:
  liumapp:
    schedule:
      datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mysql://www.liumapp.com:6603/auth_manager?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: adminadmin
        validationQuery: select 1
        validationQueryTimeout: 1000
        max-active: 30
        min-idle: 10
